kind: ReplicaSet
apiVersion: extensions/v1beta1
metadata:
  name: replicaset
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: myname, operator: In, values: [adminpod,admpod,admnpod]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      name: testpod7
      labels:
        myname: adminpod
    spec:
      containers:
        - name: c05
          image: ubuntu
          command: ["/bin/bash", "-c", "while true;do echo Hello ReplicaSets;sleep 5;done"]